//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace River.Orqa.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Browser {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Browser() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("River.Orqa.Resources.Browser", typeof(Browser).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanently delete {0}?.
        /// </summary>
        internal static string ConfirmDeleteMessage {
            get {
                return ResourceManager.GetString("ConfirmDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        internal static string ConfirmDeleteTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovering package bodies....
        /// </summary>
        internal static string DiscoveringPackageBodies {
            get {
                return ResourceManager.GetString("DiscoveringPackageBodies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovering packages....
        /// </summary>
        internal static string DiscoveringPackages {
            get {
                return ResourceManager.GetString("DiscoveringPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovering procedues....
        /// </summary>
        internal static string DiscoveringProcedures {
            get {
                return ResourceManager.GetString("DiscoveringProcedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovering sequences....
        /// </summary>
        internal static string DiscoveringSequences {
            get {
                return ResourceManager.GetString("DiscoveringSequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovering triggers....
        /// </summary>
        internal static string DiscoveringTriggers {
            get {
                return ResourceManager.GetString("DiscoveringTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovering views....
        /// </summary>
        internal static string DiscoveringViews {
            get {
                return ResourceManager.GetString("DiscoveringViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditContextMenu {
            get {
                return ResourceManager.GetString("EditContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} members.
        /// </summary>
        internal static string FolderTooltip {
            get {
                return ResourceManager.GetString("FolderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity.
        /// </summary>
        internal static string IdentityCategory {
            get {
                return ResourceManager.GetString("IdentityCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Char Length.
        /// </summary>
        internal static string PColumnCharLength {
            get {
                return ResourceManager.GetString("PColumnCharLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Length.
        /// </summary>
        internal static string PColumnDataLength {
            get {
                return ResourceManager.GetString("PColumnDataLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Type.
        /// </summary>
        internal static string PColumnDataType {
            get {
                return ResourceManager.GetString("PColumnDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PColumnFolderName {
            get {
                return ResourceManager.GetString("PColumnFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string PColumnFolderType {
            get {
                return ResourceManager.GetString("PColumnFolderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PColumnName {
            get {
                return ResourceManager.GetString("PColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullable.
        /// </summary>
        internal static string PColumnNullable {
            get {
                return ResourceManager.GetString("PColumnNullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string PColumnOwner {
            get {
                return ResourceManager.GetString("PColumnOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string PColumnTable {
            get {
                return ResourceManager.GetString("PColumnTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PConstraintFolderName {
            get {
                return ResourceManager.GetString("PConstraintFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string PConstraintFolderType {
            get {
                return ResourceManager.GetString("PConstraintFolderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate DDL.
        /// </summary>
        internal static string ScriptContextMenu {
            get {
                return ResourceManager.GetString("ScriptContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snipets.
        /// </summary>
        internal static string TemplateRoot {
            get {
                return ResourceManager.GetString("TemplateRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger Folder.
        /// </summary>
        internal static string TriggerFolderLabel {
            get {
                return ResourceManager.GetString("TriggerFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triggers.
        /// </summary>
        internal static string TriggersLabel {
            get {
                return ResourceManager.GetString("TriggersLabel", resourceCulture);
            }
        }
    }
}
