CREATE GLOBAL TEMPORARY TABLE PLAN_TABLE
(
	statement_id    varchar2(30),
	timestamp       date,
	remarks         varchar2(80),
	operation       varchar2(30),
	options         varchar2(30),
	object_node     varchar2(128),
	object_owner    varchar2(30),
	object_name     varchar2(30),
	object_instance number(38),
	object_type     varchar2(30),
	optimizer       varchar2(255),
	search_columns  number,
	id              number(38),
	parent_id       number(38),
	position        number(38),
	cost            number(38),
	cardinality     number(38),
	bytes           number(38),
	other_tag       varchar2(255),
	partition_start varchar2(255),
	partition_stop  varchar2(255),
	partition_id    number(38),
	other           long,
	distribution    varchar2(30)
) ON COMMIT DELETE ROWS;