//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace River.Orqa.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Options {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Options() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("River.Orqa.Resources.Options", typeof(Options).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        internal static string ConnectionsOptions {
            get {
                return ResourceManager.GetString("ConnectionsOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string CustomColorName {
            get {
                return ResourceManager.GetString("CustomColorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string DefaultColor {
            get {
                return ResourceManager.GetString("DefaultColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;OrqaOptions version=&quot;3.0&quot;&gt;
        ///  &lt;general resx=&quot;GeneralOptions&quot; icon=&quot;0&quot; sheet=&quot;River.Orqa.Options.GeneralSheet&quot;&gt;
        ///    &lt;queryPath&gt;&lt;/queryPath&gt;
        ///    &lt;resultPath&gt;&lt;/resultPath&gt;
        ///    &lt;templatePath&gt;&lt;/templatePath&gt;
        ///    &lt;queryExtension&gt;sql&lt;/queryExtension&gt;
        ///    &lt;resultExtension&gt;rpt&lt;/resultExtension&gt;
        ///    &lt;templateExtension&gt;tpl&lt;/templateExtension&gt;
        ///    &lt;maxMru&gt;4&lt;/maxMru&gt;
        ///    &lt;saveModified&gt;true&lt;/saveModified&gt;
        ///    &lt;savePosition&gt;true&lt;/savePosition&gt;
        ///    &lt;defaultApp&gt;true&lt;/defau [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultOptions {
            get {
                return ResourceManager.GetString("DefaultOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional.
        /// </summary>
        internal static string EditorAdditionalOptions {
            get {
                return ResourceManager.GetString("EditorAdditionalOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts and Colors.
        /// </summary>
        internal static string EditorFontOptions {
            get {
                return ResourceManager.GetString("EditorFontOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string EditorGeneralOptions {
            get {
                return ResourceManager.GetString("EditorGeneralOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        internal static string EditorOptions {
            get {
                return ResourceManager.GetString("EditorOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabs.
        /// </summary>
        internal static string EditorTabsOptions {
            get {
                return ResourceManager.GetString("EditorTabsOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error exporting options file.
        /// </summary>
        internal static string ExportError {
            get {
                return ResourceManager.GetString("ExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Error.
        /// </summary>
        internal static string ExportErrorTitle {
            get {
                return ResourceManager.GetString("ExportErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string GeneralOptions {
            get {
                return ResourceManager.GetString("GeneralOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Results.
        /// </summary>
        internal static string GridFont {
            get {
                return ResourceManager.GetString("GridFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error importing options file.
        /// </summary>
        internal static string ImportError {
            get {
                return ResourceManager.GetString("ImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Error.
        /// </summary>
        internal static string ImportErrorTitle {
            get {
                return ResourceManager.GetString("ImportErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string LexComments {
            get {
                return ResourceManager.GetString("LexComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directives.
        /// </summary>
        internal static string LexDirectives {
            get {
                return ResourceManager.GetString("LexDirectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML Tags.
        /// </summary>
        internal static string LexHtmltags {
            get {
                return ResourceManager.GetString("LexHtmltags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypertext.
        /// </summary>
        internal static string LexHypertext {
            get {
                return ResourceManager.GetString("LexHypertext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifiers.
        /// </summary>
        internal static string LexIdents {
            get {
                return ResourceManager.GetString("LexIdents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Numbers.
        /// </summary>
        internal static string LexLinenumbers {
            get {
                return ResourceManager.GetString("LexLinenumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers.
        /// </summary>
        internal static string LexNumbers {
            get {
                return ResourceManager.GetString("LexNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved words.
        /// </summary>
        internal static string LexReswords {
            get {
                return ResourceManager.GetString("LexReswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spelling Errors.
        /// </summary>
        internal static string LexSpelling {
            get {
                return ResourceManager.GetString("LexSpelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strings.
        /// </summary>
        internal static string LexStrings {
            get {
                return ResourceManager.GetString("LexStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whitespace.
        /// </summary>
        internal static string LexWhitespace {
            get {
                return ResourceManager.GetString("LexWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informational Messages.
        /// </summary>
        internal static string MessageFont {
            get {
                return ResourceManager.GetString("MessageFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;xs:schema id=&quot;OrqaOptions&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:element name=&quot;OrqaOptions&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element name=&quot;general&quot; minOccurs=&quot;0&quot; maxOccurs=&quot;1&quot;&gt;
        ///          &lt;xs:complexType&gt;
        ///            &lt;xs:sequence&gt;
        ///              &lt;xs:element name=&quot;queryPath&quot; type=&quot;xs:string&quot; minOccurs=&quot;0&quot; maxOccurs=&quot;1&quot; /&gt;
        ///              &lt;xs:element name=&quot;resultPath&quot; type=&quot;xs:string&quot; minOccurs=&quot;0&quot; maxOccurs=&quot;1&quot; /&gt;
        ///              &lt;xs:eleme [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OptionsSchema {
            get {
                return ResourceManager.GetString("OptionsSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;OutputFormat&gt;
        ///  &lt;format&gt;Column Aligned&lt;/format&gt;
        ///  &lt;format&gt;Comma Delimited (CVS)&lt;/format&gt;
        ///  &lt;format&gt;Tab Delimited&lt;/format&gt;
        ///  &lt;format&gt;Space Delimited&lt;/format&gt;
        ///  &lt;format&gt;Custom Delimeter&lt;/format&gt;
        ///&lt;/OutputFormat&gt;
        ///.
        /// </summary>
        internal static string OutputFormat {
            get {
                return ResourceManager.GetString("OutputFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;OutputTarget&gt;
        ///  &lt;target&gt;Results to Text&lt;/target&gt;
        ///  &lt;target&gt;Results to Grid&lt;/target&gt;
        ///  &lt;target&gt;Results to XML&lt;/target&gt;
        ///&lt;/OutputTarget&gt;
        ///.
        /// </summary>
        internal static string OutputTarget {
            get {
                return ResourceManager.GetString("OutputTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ParseModes&gt;
        ///  &lt;mode&gt;Prompt&lt;/mode&gt;
        ///  &lt;mode&gt;Sequential&lt;/mode&gt;
        ///  &lt;mode&gt;Block&lt;/mode&gt;
        ///  &lt;mode&gt;Wrapped&lt;/mode&gt;
        ///&lt;/ParseModes&gt;
        ///.
        /// </summary>
        internal static string ParseModes {
            get {
                return ResourceManager.GetString("ParseModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query File Folder.
        /// </summary>
        internal static string QueryFileFolder {
            get {
                return ResourceManager.GetString("QueryFileFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Results Folder.
        /// </summary>
        internal static string QueryResultsFolder {
            get {
                return ResourceManager.GetString("QueryResultsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Template Folder.
        /// </summary>
        internal static string QueryTemplateFolder {
            get {
                return ResourceManager.GetString("QueryTemplateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all options to system default values?.
        /// </summary>
        internal static string ResetPrompt {
            get {
                return ResourceManager.GetString("ResetPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string ResetPromptTitle {
            get {
                return ResourceManager.GetString("ResetPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts.
        /// </summary>
        internal static string ResultsFontOptions {
            get {
                return ResourceManager.GetString("ResultsFontOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string ResultsGeneralOptions {
            get {
                return ResourceManager.GetString("ResultsGeneralOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string ResultsOptions {
            get {
                return ResourceManager.GetString("ResultsOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string StatisticsOptions {
            get {
                return ResourceManager.GetString("StatisticsOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text and XML Results.
        /// </summary>
        internal static string TextFont {
            get {
                return ResourceManager.GetString("TextFont", resourceCulture);
            }
        }
    }
}
