//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace River.Orqa.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Orqa {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Orqa() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("River.Orqa.Resources.Orqa", typeof(Orqa).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser.
        /// </summary>
        internal static string BrowserWindowTitle {
            get {
                return ResourceManager.GetString("BrowserWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection state changed from {0} to {1}.
        /// </summary>
        internal static string ConnectionStateChange {
            get {
                return ResourceManager.GetString("ConnectionStateChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide &amp;Debugger.
        /// </summary>
        internal static string HideDebuggerMenu {
            get {
                return ResourceManager.GetString("HideDebuggerMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide &amp;Object Browser.
        /// </summary>
        internal static string HideObjectBrowserMenu {
            get {
                return ResourceManager.GetString("HideObjectBrowserMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Object Properties.
        /// </summary>
        internal static string HidePropertiesMenu {
            get {
                return ResourceManager.GetString("HidePropertiesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1033\deflangfe1033\themelang1033\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f2\fbidi \fmodern\fcharset0\fprq1{\*\panose 02070309020205020404}Courier New;}
        ///{\f3\fbidi \froman\fcharset2\fprq2{\*\panose 05050102010706020507}Symbol;}{\f10\fbidi \fnil\fcharset2\fprq2{\*\panose 05000000000000000000}Wingdings;}{\f10\fbidi \fnil\fcharset2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct connection resulted in a TNS protocol exception.  This is typically a result\nof a missing ORACLE_SID entry in either the Registry or the environment variables..
        /// </summary>
        internal static string MissingSidError {
            get {
                return ResourceManager.GetString("MissingSidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orqa requires the Oracle Data Provider for .NET\nDownload ODP.NET from www.oracle.com and install before running Orqa..
        /// </summary>
        internal static string OdpNotInstalledMsg {
            get {
                return ResourceManager.GetString("OdpNotInstalledMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ODP.NET Not Found.
        /// </summary>
        internal static string OdpNotInstalledTitle {
            get {
                return ResourceManager.GetString("OdpNotInstalledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orqa Files (*.{0};*.{1})|*.{0};*.{1}|Query File (*.{0})|*.{0}|Project File (*.{1})|*.{1}|All Files (*.*)|*.*.
        /// </summary>
        internal static string OpenFileDialogFilter {
            get {
                return ResourceManager.GetString("OpenFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project File (*.{0})|*.{0}|All Files (*.*)|*.*.
        /// </summary>
        internal static string OpenScriptDialogFilter {
            get {
                return ResourceManager.GetString("OpenScriptDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orqa requires Oracle\nIt is the Oracle Query Analyzer after all!.
        /// </summary>
        internal static string OracleNotInstalledMsg {
            get {
                return ResourceManager.GetString("OracleNotInstalledMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oracle Not Found.
        /// </summary>
        internal static string OracleNotInstalledTitle {
            get {
                return ResourceManager.GetString("OracleNotInstalledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments found on same line as query, Ln {0} Col {1}.
        /// </summary>
        internal static string ParseCommentError {
            get {
                return ResourceManager.GetString("ParseCommentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string PropertiesWindowTitle {
            get {
                return ResourceManager.GetString("PropertiesWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query File (*.sql)|*.sql|All Files (*.*)|*.*.
        /// </summary>
        internal static string SaveQueryDialogFilter {
            get {
                return ResourceManager.GetString("SaveQueryDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Query.
        /// </summary>
        internal static string SaveQueryDialogTitle {
            get {
                return ResourceManager.GetString("SaveQueryDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report File (*.txt)|*.txt|All Files (*.*)|*.*.
        /// </summary>
        internal static string SaveReportDialogFilter {
            get {
                return ResourceManager.GetString("SaveReportDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Report.
        /// </summary>
        internal static string SaveReportDialogTitle {
            get {
                return ResourceManager.GetString("SaveReportDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient access to read system registry.  You may be running Orqa from a network share; if so, try running it from a local drive..
        /// </summary>
        internal static string SecurityExceptionMsg {
            get {
                return ResourceManager.GetString("SecurityExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Exception.
        /// </summary>
        internal static string SecurityExceptionTitle {
            get {
                return ResourceManager.GetString("SecurityExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;Debugger.
        /// </summary>
        internal static string ShowDebuggerMenu {
            get {
                return ResourceManager.GetString("ShowDebuggerMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;Object Browser.
        /// </summary>
        internal static string ShowObjectBrowserMenu {
            get {
                return ResourceManager.GetString("ShowObjectBrowserMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Object Properties.
        /// </summary>
        internal static string ShowPropertiesMenu {
            get {
                return ResourceManager.GetString("ShowPropertiesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections: {0}.
        /// </summary>
        internal static string StatusConnections {
            get {
                return ResourceManager.GetString("StatusConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace.
        /// </summary>
        internal static string TraceWindowTitle {
            get {
                return ResourceManager.GetString("TraceWindowTitle", resourceCulture);
            }
        }
    }
}
