//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace River.Orqa.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Query {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Query() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("River.Orqa.Resources.Query", typeof(Query).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ln {0}, Col {1}.
        /// </summary>
        internal static string CaretStatusText {
            get {
                return ResourceManager.GetString("CaretStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caret Position: Ln {0}, Col {1}.
        /// </summary>
        internal static string CaretStatusTooltip {
            get {
                return ResourceManager.GetString("CaretStatusTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed..
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing....
        /// </summary>
        internal static string ExecutingStatus {
            get {
                return ResourceManager.GetString("ExecutingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution time: {0}.
        /// </summary>
        internal static string ExecutionTime {
            get {
                return ResourceManager.GetString("ExecutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No messages to report..
        /// </summary>
        internal static string NoMessages {
            get {
                return ResourceManager.GetString("NoMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content is not executable.
        /// </summary>
        internal static string NotExecutableStatusMsg {
            get {
                return ResourceManager.GetString("NotExecutableStatusMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string ReadyStatus {
            get {
                return ResourceManager.GetString("ReadyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} row(s) affected).
        /// </summary>
        internal static string RowsAffected {
            get {
                return ResourceManager.GetString("RowsAffected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;XmlSyntaxSettingsInfo xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;FontName&gt;Lucida Console&lt;/FontName&gt;
        ///  &lt;FontSize&gt;8&lt;/FontSize&gt;
        ///  &lt;FontStyle&gt;Regular&lt;/FontStyle&gt;
        ///  &lt;NavOptions&gt;UpAtLineBegin DownAtLineEnd&lt;/NavOptions&gt;
        ///  &lt;ScrollBars&gt;ForcedBoth&lt;/ScrollBars&gt;
        ///  &lt;SelOptions&gt;OverwriteBlocks&lt;/SelOptions&gt;
        ///  &lt;GutterOptions&gt;PaintLinesOnGutter&lt;/GutterOptions&gt;
        ///  &lt;OutlineOptions&gt;None&lt;/OutlineOptions&gt;
        ///  &lt;ShowGutter&gt;tr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqlSettings {
            get {
                return ResourceManager.GetString("SqlSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;LexScheme xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;Author&gt;Steven M. Cohn&lt;/Author&gt;
        ///  &lt;Name&gt;SQL(Oracle)&lt;/Name&gt;
        ///  &lt;Desc&gt;Syntax Scheme for SQL(Oracle) Language&lt;/Desc&gt;
        ///  &lt;Copyright&gt;Copyright Steven M. Cohn, 2002-2005&lt;/Copyright&gt;
        ///  &lt;Version&gt;1.0&lt;/Version&gt;
        ///  &lt;Styles&gt;
        ///    &lt;LexStyle&gt;
        ///      &lt;Name&gt;idents&lt;/Name&gt;
        ///      &lt;ForeColor&gt;ControlText&lt;/ForeColor&gt;
        ///      &lt;Index&gt;0&lt;/Index&gt;
        ///    &lt;/LexStyle&gt;
        ///    &lt;LexStyle&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqlStyle {
            get {
                return ResourceManager.GetString("SqlStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement ignored ({0}).
        /// </summary>
        internal static string StatementIgnored {
            get {
                return ResourceManager.GetString("StatementIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;XmlSyntaxSettingsInfo xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;FontName&gt;Lucida Console&lt;/FontName&gt;
        ///  &lt;FontSize&gt;8&lt;/FontSize&gt;
        ///  &lt;FontStyle&gt;Regular&lt;/FontStyle&gt;
        ///  &lt;NavOptions&gt;UpAtLineBegin DownAtLineEnd&lt;/NavOptions&gt;
        ///  &lt;ScrollBars&gt;ForcedBoth&lt;/ScrollBars&gt;
        ///  &lt;SelOptions&gt;OverwriteBlocks&lt;/SelOptions&gt;
        ///  &lt;GutterOptions&gt;PaintLinesOnGutter&lt;/GutterOptions&gt;
        ///  &lt;OutlineOptions&gt;None&lt;/OutlineOptions&gt;
        ///  &lt;ShowGutter&gt;tr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TextSettings {
            get {
                return ResourceManager.GetString("TextSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;LexScheme xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;Author&gt;Steven M. Cohn&lt;/Author&gt;
        ///  &lt;Name&gt;PlainText&lt;/Name&gt;
        ///  &lt;Desc&gt;Syntax Scheme for SQL(Oracle) Language&lt;/Desc&gt;
        ///  &lt;Copyright&gt;Copyright Steven M. Cohn, 2002-2005&lt;/Copyright&gt;
        ///  &lt;Version&gt;1.0&lt;/Version&gt;
        ///  &lt;Styles&gt;
        ///    &lt;LexStyle&gt;
        ///      &lt;Name&gt;idents&lt;/Name&gt;
        ///      &lt;ForeColor&gt;ControlText&lt;/ForeColor&gt;
        ///      &lt;BackColor /&gt;
        ///      &lt;FontStyle&gt;Regular&lt;/FontStyle&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TextStyle {
            get {
                return ResourceManager.GetString("TextStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} total row(s) affected).
        /// </summary>
        internal static string TotalRowsAffected {
            get {
                return ResourceManager.GetString("TotalRowsAffected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized statement type ({0}).
        /// </summary>
        internal static string UnrecognizedQueryType {
            get {
                return ResourceManager.GetString("UnrecognizedQueryType", resourceCulture);
            }
        }
    }
}
