SELECT CON_ITEM.ITEMID,
  CON_ITEM.ITEMDATAID,
  CON_ITEM.ISSUBITEM,
  CON_ITEM.ITEMROOTID,
  CON_ITEM.VERSIONNO,
  CON_ITEM.ISLASTVERSION,
  CON_ITEM.DATANODEID,
  CON_ITEM.ITEMTYPEID,
  Con_Itemtype.NAME,
  CON_ITEM.COMMONNAME,
  CON_ITEM.COMMONSYSTEMNAME,
  CON_ITEM.COMMONSYSTEMTYPE,
  CON_ITEM.NATIVEAPP,
  CON_ITEM.PREVIOUSSTATE,
  CON_ITEM.STATE,
  CON_ITEM.STATEMODIFIEDDTTM,
  CON_ITEM.STATEMODIFIERID,
  CON_ITEM.INSTANCEDATAMODIFIEDDTTM,
  CON_ITEM.INSTANCEDATAMODIFIERID,
  CON_ITEM.EXCLUSIVEEDITLOCK,
  CON_ITEM.VERSIONLOCKDTTM,
  CON_ITEM.VERSIONLOCKUSERID,
  CON_ITEM.VERSIONLOCK,
  CON_ITEM.CREATEDDTTM,
  CON_ITEM.CREATORID,
  CON_ITEM.CREATORNAME,
  CON_ITEM.MODIFIEDDTTM,
  CON_ITEM.MODVERSION,
  CON_ITEMRELATION.RELATEDITEMID,
  CON_ITEMRELATION.RELATIONTYPE
FROM CON_ITEM,
  Con_Itemtype,
  CON_ITEMRELATION
WHERE (CON_ITEM.ITEMTYPEID     = Con_Itemtype.ITEMTYPEID)
AND CON_ITEM.ITEMID            = CON_ITEMRELATION.RELATEDITEMID(+)
AND CON_ITEMRELATION.ITEMID(+) = CON_ITEM.ITEMID
AND (CON_ITEM.MODIFIEDDTTM     > SysDate - 28)
ORDER BY CON_ITEM.CREATEDDTTM DESC;