namespace River.Orqa.Editor
{
    using River.Orqa.Editor.Common;
    using System;
    using System.Drawing;
    using System.Windows.Forms;

    public class EditConsts
    {
        // Methods
        static EditConsts()
        {
            EditConsts.DefaultOutlineOptions = OutlineOptions.ShowHints | (OutlineOptions.DrawButtons | OutlineOptions.DrawLines);
            EditConsts.DefaultGutterOptions = GutterOptions.PaintBookMarks;
            EditConsts.DefaultCodeCompletionFlags = CodeCompletionFlags.AcceptOnDelimiter | (CodeCompletionFlags.FeetToScreen | (CodeCompletionFlags.AcceptOnDblClick | (CodeCompletionFlags.CloseOnLostFocus | (CodeCompletionFlags.CloseOnMouseLeave | (CodeCompletionFlags.AcceptOnEnter | CodeCompletionFlags.CloseOnEscape)))));
            EditConsts.DefaultPrintOptions = PrintOptions.DisplayProgress | (PrintOptions.UseFooter | (PrintOptions.UseHeader | (PrintOptions.UseSyntax | (PrintOptions.UseColors | (PrintOptions.WordWrap | (PrintOptions.PageNumbers | PrintOptions.LineNumbers))))));
            EditConsts.DefaultSelectionOptions = SelectionOptions.SmartFormat | SelectionOptions.OverwriteBlocks;
            EditConsts.DefaultNavigateOptions = NavigateOptions.DownAtLineEnd | NavigateOptions.UpAtLineBegin;
            EditConsts.DefaultIndentOptions = IndentOptions.SmartIndent | IndentOptions.AutoIndent;
            EditConsts.DefaultUndoOptions = UndoOptions.UndoAfterSave | (UndoOptions.GroupUndo | UndoOptions.AllowUndo);
            EditConsts.DefaultSearchOptions = SearchOptions.FindTextAtCursor;
            EditConsts.DefaultLineStyleOptions = LineStyleOptions.InvertColors;
            EditConsts.DefaultRulerOptions = RulerOptions.DisplayDragLine | (RulerOptions.AllowDrag | RulerOptions.Discrete);
            EditConsts.DefaultSelectionMode = AllowedSelectionMode.Block | AllowedSelectionMode.Stream;
            EditConsts.DefaultBracesForeColor = Color.Black;
            EditConsts.DefaultArrowBackColor = Color.Silver;
            EditConsts.DefaultArrowForeColor = Color.Black;
            EditConsts.DefaultLineBookmarksColor = Color.Red;
            EditConsts.DefaultLineNumbersForeColor = SystemColors.WindowText;
            EditConsts.DefaultLineNumbersBackColor = Color.LightGray;
            EditConsts.DefaultLineStyleForeColor = SystemColors.WindowText;
            EditConsts.DefaultLineStyleBackColor = SystemColors.Window;
            EditConsts.DefaultPrintHeaderForeColor = Color.Black;
            EditConsts.DefaultTransparentColor = Color.Fuchsia;
            EditConsts.DefaultUrlForeColor = Color.Blue;
            EditConsts.DefaultGutterBackColor = Color.LightGray;
            EditConsts.DefaultGutterForeColor = Color.Gray;
            EditConsts.DefaultDisabledForeColor = SystemColors.GrayText;
            EditConsts.DefaultInfoBackColor = SystemColors.Info;
            EditConsts.DefaultLineSeparatorColor = SystemColors.ScrollBar;
            EditConsts.DefaultLineSeparatorLineColor = SystemColors.ControlText;
            EditConsts.DefaultHighlightForeColor = SystemColors.HighlightText;
            EditConsts.DefaultHighlightBackColor = SystemColors.Highlight;
            EditConsts.DefaultInactiveHighlightForeColor = SystemColors.InactiveCaptionText;
            EditConsts.DefaultInactiveHighlightBackColor = SystemColors.InactiveCaption;
            EditConsts.DefaultMarginForeColor = Color.Gray;
            EditConsts.DefaultOutlineForeColor = Color.DarkGray;
            EditConsts.DefaultSpellForeColor = Color.Red;
            EditConsts.DefaultHeaderFontColor = Color.LightGray;
            EditConsts.DefaultRulerBackColor = SystemColors.Control;
            EditConsts.DefaultRulerIndentBackColor = SystemColors.ControlDark;
            EditConsts.DefaultPageBackColor = SystemColors.ControlDark;
            EditConsts.DefaultPageBorderColor = SystemColors.WindowFrame;
            EditConsts.DefaultReswordForeColor = Color.Blue;
            EditConsts.DefaultCommentsForeColor = Color.Green;
            EditConsts.DefaultStringsForeColor = Color.Maroon;
            EditConsts.DefaultDirectivesForeColor = Color.DarkGreen;
            EditConsts.DefaultXmlCommentsForeColor = Color.Gray;
            EditConsts.DefaultHtmlTagsForeColor = Color.Maroon;
            EditConsts.DefaultHyperTextForeColor = Color.Blue;
            EditConsts.DefaultWhiteSpaceForeColor = Color.Teal;
            EditConsts.DefaultBracesFontStyle = FontStyle.Bold;
            EditConsts.DefaultHeaderFontStyle = FontStyle.Regular;
            EditConsts.DefaultUrlFontStyle = FontStyle.Underline;
            EditConsts.DefaultCommentsFontStyle = FontStyle.Italic;
            EditConsts.DefaultOpenBraces = new char[3] { '(', '[', '{' } ;
            EditConsts.DefaultClosingBraces = new char[3] { ')', ']', '}' } ;
            EditConsts.DefaultCaretSymbol = '|';
            EditConsts.DefaultOutlineText = "...";
            EditConsts.DefaultHyperTextHint = "{0}" + Consts.CRLF + "Ctrl + Click to follow link";
            EditConsts.DefaultDragMarginHint = "Ctrl + Click to drag the margin";
            EditConsts.EmptyOption = "None";
            EditConsts.DefaultDelimiters = ";.,:'\"{}[]()?!@#$%^&*-+=|\\/";
            EditConsts.DefaultUrlChars = "_.:/@-?=~";
            EditConsts.DefaultSpellDelimiters = EditConsts.DefaultDelimiters;
            EditConsts.PrintOptionsButtonText = "&Options";
            EditConsts.InvalidTypeName = "Invalid Type Name: {0}";
            EditConsts.InvalidPropName = "Invalid Property Name: {0}";
            EditConsts.InvalidTabStop = "Invalid Tab Stops: {0}";
            EditConsts.InvalidReference = "Invalid Object Reference: {0}";
            EditConsts.InvalidRange = "Can't create intersecting outline section. Range :{0}, {1}";
            EditConsts.StringNotFound = "The specified text was not found. Text : {0}";
            EditConsts.MailTo = "MAILTO:";
            EditConsts.WWW = "WWW.";
            EditConsts.HTTPProtocol = "HTTP://";
            EditConsts.FTPProtocol = "FTP://";
            EditConsts.GopherProtocol = "GOPHER://";
            EditConsts.FileProtocol = "FILE://";
            EditConsts.SearchDlgCaption = "Find";
            EditConsts.ReplaceDlgCaption = "Replace";
            EditConsts.LineNumberCaption = "Line number ({0} - {1})";
            EditConsts.PageTag = @"\[page]";
            EditConsts.PagesTag = @"\[pages]";
            EditConsts.DateTag = @"\[date]";
            EditConsts.TimeTag = @"\[time]";
            EditConsts.UserTag = @"\[username]";
            EditConsts.HeaderFontName = "Times New";
            EditConsts.DefaultPageHorzOffset = 0x40;
            EditConsts.DefaultPageVertOffset = 0x18;
            EditConsts.TabSymbol = '\x00bb';
            EditConsts.SpaceSymbol = '\x00b7';
            EditConsts.EolSymbol = '\x00b6';
            EditConsts.EofSymbol = '_';
            EditConsts.NofMstr = "{0} of {1}";
            EditConsts.LineNofMstr = "Line {0} of {1}";
            EditConsts.LineStr = "Line";
            EditConsts.PageNofMstr = "Page {0} of {1}";
            EditConsts.PageStr = "Page";
            EditConsts.DottedText = "...";
            EditConsts.DefaultCodeCompletionChars = ".(";
            EditConsts.DefaultDropDownCount = 8;
            EditConsts.MaxDropDownCount = 0x10;
            EditConsts.DefaultMinListBoxWidth = 50;
            EditConsts.DefaultMinListBoxHeight = 50;
            EditConsts.MaxHintWindowWidth = (Screen.PrimaryScreen.Bounds.Width * 2) / 3;
            EditConsts.MaxHintWindowCount = 20;
            EditConsts.DefaultHintOffsetX = 8;
            EditConsts.DefaultHintOffsetY = 4;
            EditConsts.DefaultSpacesInTab = 4;
            EditConsts.DefaultRulerHeight = 0x1c;
            EditConsts.DefaultRulerIndentSize = 2;
            EditConsts.DefaultRulerHitWidth = 4;
            EditConsts.DefaultRulerMinWidth = 40;
            EditConsts.DefaultRulerUnits = RulerUnits.Inches;
            EditConsts.DefaultRulerFontName = "Arial";
            EditConsts.DefaultRulerFontSize = 7f;
            EditConsts.DefaultCaretWidth = 2;
            EditConsts.DefaultHorzScrollSize = 0xff;
            EditConsts.DefaultGutterWidth = 0x10;
            EditConsts.DefaultMarginPosition = 80;
            EditConsts.DefaultMarginHitWidth = 4;
            EditConsts.DefaultTabStop = 4;
            EditConsts.DefaultParserDelta = 0x80;
            EditConsts.DefaultSelDelay = 0x20;
            EditConsts.DefaultDragDelay = 500;
            EditConsts.DefaultOutlineDelay = 1000;
            EditConsts.DefaultBracesDelay = 2000;
            EditConsts.DefaultHideHintDelay = 2500;
            EditConsts.DefaultWrapDelta = 0x80;
            EditConsts.DefaultCollasedImageWidth = 8;
            EditConsts.DefaultColumnSeparator = 2;
            EditConsts.DefaultRowSeparator = 2;
            EditConsts.DefaultLineNumbersStart = 1;
            EditConsts.DefaultLineNumbersIndent = 2;
            EditConsts.DefaultBookMarkImageIndex = 10;
            EditConsts.DefaultWrapImageIndex = 13;
            Keys[] keysArray1 = new Keys[9] { Keys.Left, Keys.Right, Keys.Up, Keys.Down, Keys.Prior, Keys.Next, Keys.End, Keys.Home, Keys.Tab } ;
            EditConsts.NavKeys = keysArray1;
        }

        public EditConsts()
        {
        }


        // Fields
        public static string DateTag;
        public static Color DefaultArrowBackColor;
        public static Color DefaultArrowForeColor;
        public static int DefaultBookMarkImageIndex;
        public const EditBorderStyle DefaultBorderStyle = EditBorderStyle.Fixed3D;
        public static int DefaultBracesDelay;
        public static FontStyle DefaultBracesFontStyle;
        public static Color DefaultBracesForeColor;
        public static char DefaultCaretSymbol;
        public static int DefaultCaretWidth;
        public static char[] DefaultClosingBraces;
        public static string DefaultCodeCompletionChars;
        public static CodeCompletionFlags DefaultCodeCompletionFlags;
        public static int DefaultCollasedImageWidth;
        public static int DefaultColumnSeparator;
        public static FontStyle DefaultCommentsFontStyle;
        public static Color DefaultCommentsForeColor;
        public static string DefaultDelimiters;
        public static Color DefaultDirectivesForeColor;
        public static Color DefaultDisabledForeColor;
        public static int DefaultDragDelay;
        public static string DefaultDragMarginHint;
        public static int DefaultDropDownCount;
        public static Color DefaultGutterBackColor;
        public static Color DefaultGutterForeColor;
        public static GutterOptions DefaultGutterOptions;
        public static int DefaultGutterWidth;
        public static Color DefaultHeaderFontColor;
        public static FontStyle DefaultHeaderFontStyle;
        public static int DefaultHideHintDelay;
        public static Color DefaultHighlightBackColor;
        public static Color DefaultHighlightForeColor;
        public static int DefaultHintOffsetX;
        public static int DefaultHintOffsetY;
        public static int DefaultHorzScrollSize;
        public static Color DefaultHtmlTagsForeColor;
        public static Color DefaultHyperTextForeColor;
        public static string DefaultHyperTextHint;
        public static Color DefaultInactiveHighlightBackColor;
        public static Color DefaultInactiveHighlightForeColor;
        public static IndentOptions DefaultIndentOptions;
        public static Color DefaultInfoBackColor;
        public static Color DefaultLineBookmarksColor;
        public static Color DefaultLineNumbersBackColor;
        public static Color DefaultLineNumbersForeColor;
        public static int DefaultLineNumbersIndent;
        public static int DefaultLineNumbersStart;
        public static Color DefaultLineSeparatorColor;
        public static Color DefaultLineSeparatorLineColor;
        public static Color DefaultLineStyleBackColor;
        public static Color DefaultLineStyleForeColor;
        public static LineStyleOptions DefaultLineStyleOptions;
        public static Color DefaultMarginForeColor;
        public static int DefaultMarginHitWidth;
        public static int DefaultMarginPosition;
        public static int DefaultMinListBoxHeight;
        public static int DefaultMinListBoxWidth;
        public static NavigateOptions DefaultNavigateOptions;
        public static char[] DefaultOpenBraces;
        public static int DefaultOutlineDelay;
        public static Color DefaultOutlineForeColor;
        public static OutlineOptions DefaultOutlineOptions;
        public static string DefaultOutlineText;
        public static Color DefaultPageBackColor;
        public static Color DefaultPageBorderColor;
        public static int DefaultPageHorzOffset;
        public static int DefaultPageVertOffset;
        public static int DefaultParserDelta;
        public static Color DefaultPrintHeaderForeColor;
        public const int DefaultPrintHeaderOffsetX = 0x18;
        public const int DefaultPrintHeaderOffsetY = 8;
        public static PrintOptions DefaultPrintOptions;
        public static Color DefaultReswordForeColor;
        public static int DefaultRowSeparator;
        public static Color DefaultRulerBackColor;
        public static string DefaultRulerFontName;
        public static float DefaultRulerFontSize;
        public static int DefaultRulerHeight;
        public static int DefaultRulerHitWidth;
        public static Color DefaultRulerIndentBackColor;
        public static int DefaultRulerIndentSize;
        public static int DefaultRulerMinWidth;
        public static RulerOptions DefaultRulerOptions;
        public static RulerUnits DefaultRulerUnits;
        public static SearchOptions DefaultSearchOptions;
        public static int DefaultSelDelay;
        public static AllowedSelectionMode DefaultSelectionMode;
        public static SelectionOptions DefaultSelectionOptions;
        public static int DefaultSpacesInTab;
        public static string DefaultSpellDelimiters;
        public static Color DefaultSpellForeColor;
        public static Color DefaultStringsForeColor;
        public static int DefaultTabStop;
        public static Color DefaultTransparentColor;
        public static UndoOptions DefaultUndoOptions;
        public static string DefaultUrlChars;
        public static FontStyle DefaultUrlFontStyle;
        public static Color DefaultUrlForeColor;
        public static Color DefaultWhiteSpaceForeColor;
        public static int DefaultWrapDelta;
        public static int DefaultWrapImageIndex;
        public static Color DefaultXmlCommentsForeColor;
        public static string DottedText;
        public static string EmptyOption;
        public static char EofSymbol;
        public static char EolSymbol;
        public static string FileProtocol;
        public static string FTPProtocol;
        public static string GopherProtocol;
        public static string HeaderFontName;
        public static string HTTPProtocol;
        public static string InvalidPropName;
        public static string InvalidRange;
        public static string InvalidReference;
        public static string InvalidTabStop;
        public static string InvalidTypeName;
        public static string LineNofMstr;
        public static string LineNumberCaption;
        public static string LineStr;
        public static string MailTo;
        public static int MaxDropDownCount;
        public static int MaxHintWindowCount;
        public static int MaxHintWindowWidth;
        public const int MinPageIndent = 4;
        public static Keys[] NavKeys;
        public static string NofMstr;
        public static string PageNofMstr;
        public static string PagesTag;
        public static string PageStr;
        public static string PageTag;
        public static string PrintOptionsButtonText;
        public static string ReplaceDlgCaption;
        public static string SearchDlgCaption;
        public static char SpaceSymbol;
        public static string StringNotFound;
        public static char TabSymbol;
        public static string TimeTag;
        public static string UserTag;
        public const int WheelDelta = 120;
        public static string WWW;
    }
}

