
ALTER SESSION
  { ADVISE { COMMIT | ROLLBACK | NOTHING }
  | CLOSE DATABASE LINK dblink
  | { ENABLE | DISABLE } COMMIT IN PROCEDURE
  | { ENABLE | DISABLE | FORCE } PARALLEL
      { DML | DDL | QUERY } [ PARALLEL integer ]
  | { ENABLE RESUMABLE [ TIMEOUT integer ] [ NAME string ]
    | DISABLE RESUMABLE
    }
  | SET parameter_name = parameter_value [ parameter_name = parameter_value ]...
      [ COMMENT = 'text' ]
  } ;

parameter_name =
	CURSOR_SHARING
	DB_BLOCK_CHECKING
	DB_CREATE_FILE_DEST
	DB_CREATE_ONLINE_LOG_DEST_n
	DB_FILE_MULTIBLOCK_READ_COUNT
	FILESYSTEMIO_OPTIONS
	GLOBAL_NAMES
	HASH_AREA_SIZE
	HASH_JOIN_ENABLED
	LOG_ARCHIVE_DEST_n
	LOG_ARCHIVE_DEST_STATE_n
	LOG_ARCHIVE_MIN_SUCCEED_DEST
	MAX_DUMP_FILE_SIZE
	NLS_CALENDAR
	NLS_COMP
	NLS_CURRENCY
	NLS_DATE_FORMAT
	NLS_DATE_LANGUAGE
	NLS_DUAL_CURRENCY
	NLS_ISO_CURRENCY
	NLS_LANGUAGE
	NLS_LENGTH_SEMANTICS
	NLS_NCHAR_CONV_EXCP
	NLS_NUMERIC_CHARACTERS
	NLS_SORT
	NLS_TERRITORY
	NLS_TIMESTAMP_FORMAT
	NLS_TIMESTAMP_TZ_FORMAT
	OBJECT_CACHE_MAX_SIZE_PERCENT
	OBJECT_CACHE_OPTIMAL_SIZE
	OLAP_PAGE_POOL_SIZE
	OPTIMIZER_DYNAMIC_SAMPLING
	OPTIMIZER_INDEX_CACHING
	OPTIMIZER_INDEX_COST_ADJ
	OPTIMIZER_MAX_PERMUTATIONS
	OPTIMIZER_MODE
	ORACLE_TRACE_ENABLE
	PARALLEL_INSTANCE_GROUP
	PARALLEL_MIN_PERCENT
	PARTITION_VIEW_ENABLED
	PLSQL_COMPILER_FLAGS
	QUERY_REWRITE_ENABLED
	QUERY_REWRITE_INTEGRITY
	REMOTE_DEPENDENCIES_MODE
	SESSION_CACHED_CURSORS
	SORT_AREA_RETAINED_SIZE
	SORT_AREA_SIZE
	STAR_TRANSFORMATION_ENABLED
	STATISTICS_LEVEL
	TIMED_OS_STATISTICS
	TIMED_STATISTICS
	TRACE_ENABLED
	UNDO_SUPPRESS_ERRORS
	WORKAREA_SIZE_POLICY 
