//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace River.Orqa.Resources.Dialogs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NewItems {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NewItems() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("River.Orqa.Resources.Dialogs.NewItems", typeof(NewItems).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BatchFile {
            get {
                object obj = ResourceManager.GetObject("BatchFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Package {
            get {
                object obj = ResourceManager.GetObject("Package", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Package.sql.
        /// </summary>
        internal static string Package_sql {
            get {
                return ResourceManager.GetString("Package_sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- PackageBody.sql.
        /// </summary>
        internal static string PackageBody_sql {
            get {
                return ResourceManager.GetString("PackageBody_sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rem Script.bat.
        /// </summary>
        internal static string Script_bat {
            get {
                return ResourceManager.GetString("Script_bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;templates&gt;
        ///  &lt;template&gt;
        ///    &lt;icon&gt;BatchFile&lt;/icon&gt;
        ///    &lt;name&gt;Build Component&lt;/name&gt;
        ///    &lt;description&gt;Batch script for standard component data models.&lt;/description&gt;
        ///    &lt;filename&gt;Build.bat&lt;/filename&gt;
        ///    &lt;resID&gt;Script_bat&lt;/resID&gt;
        ///  &lt;/template&gt;
        ///  &lt;template&gt;
        ///    &lt;icon&gt;SqlScript&lt;/icon&gt;
        ///    &lt;name&gt;Build Schema&lt;/name&gt;
        ///    &lt;description&gt;SQL script for standard component data models.&lt;/description&gt;
        ///    &lt;filename&gt;Build.sql&lt;/filename&gt;
        ///    &lt;resID&gt;SqlScript_sql&lt;/resID [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqlProjectItems {
            get {
                return ResourceManager.GetString("SqlProjectItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SqlScript {
            get {
                object obj = ResourceManager.GetObject("SqlScript", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- SqlScript.sql.
        /// </summary>
        internal static string SqlScript_sql {
            get {
                return ResourceManager.GetString("SqlScript_sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Table {
            get {
                object obj = ResourceManager.GetObject("Table", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Table.sql.
        /// </summary>
        internal static string Table_sql {
            get {
                return ResourceManager.GetString("Table_sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TextFile {
            get {
                object obj = ResourceManager.GetObject("TextFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap View {
            get {
                object obj = ResourceManager.GetObject("View", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- View.sql.
        /// </summary>
        internal static string View_sql {
            get {
                return ResourceManager.GetString("View_sql", resourceCulture);
            }
        }
    }
}
